:terms:
    - :term: 'Africa and The New World'
      :id: 'UA005.018'
    - :term: 'Biopsychology (interdisciplinary major)'
      :id: 'UA005.037'
    - :term: 'Dept. of Biology'
      :id: 'UA005.010'
    - :term: 'Dept. of Biomedical Engineering'
      :id: 'UA005.019'
    - :term: 'Dept. of Child Development'
      :id: 'UA005.009'
    - :term: 'Dept. of Civil Engineering'
      :id: 'UA005.040'
    - :term: 'Dept. of Classics'
      :id: 'UA005.025'
    - :term: 'Dept. of Computer Science'
      :id: 'UA005.036'
    - :term: 'Dept. of Drama and Dance'
      :id: 'UA005.026'
    - :term: 'Dept. of Economics'
      :id: 'UA005.003'
    - :term: 'Dept. of Electrical and Computer Engineering'
      :id: 'UA005.035'
    - :term: 'Dept. of English'
      :id: 'UA005.005'
    - :term: 'Dept. of Geology'
      :id: 'UA005.038'
    - :term: 'Dept. of History'
      :id: 'UA005.001'
    - :term: 'Dept. of International Letters and Visual Studies'
      :id: 'UA005.033'
    - :term: 'Dept. of Mathematics'
      :id: 'UA005.032'
    - :term: 'Dept. of Mechanical Engineering'
      :id: 'UA005.028'
    - :term: 'Dept. of Music'
      :id: 'UA005.034'
    - :term: 'Dept. of Philosophy'
      :id: 'UA005.002'
    - :term: 'Dept. of Physics'
      :id: 'UA005.022'
    - :term: 'Dept. of Political Science'
      :id: 'UA005.007'
    - :term: 'Dept. of Psychology'
      :id: 'UA005.006'
    - :term: 'Dept. of Religion'
      :id: 'UA005.024'
    - :term: 'Dept. of Romance Languages'
      :id: 'UA005.020'
    - :term: 'Dept. of Sociology/Anthropology'
      :id: 'UA005.011'
    - :term: 'Dept. of Chemical and Bio Engineering'
      :id: 'UA005.012'
    - :term: 'Dept. of Art and Art History'
      :id: 'UA005.013'
    - :term: 'Dept. of German, Russian, and Asian Languages and Literature'
      :id: 'UA005.014'
    - :term: 'Dept. of Chemistry'
      :id: 'UA005.015'
    - :term: 'Plan of Study'
      :id: 'UA005.016'
    - :term: 'Program in American Studies'
      :id: 'UA005.008'
    - :term: 'Program in Archaeology'
      :id: 'UA005.030'
    - :term: 'Program in Asian Studies'
      :id: 'UA005.017'
    - :term: 'Program in Community Health'
      :id: 'UA005.031'
    - :term: 'Program in Engineering Psychology'
      :id: 'UA005.029'
    - :term: 'Program in International Relations'
      :id: 'UA005.004'
    - :term: 'Program in Judaic Studies'
      :id: 'UA005.023'
    - :term: 'Program in Peace and Justice Studies'
      :id: 'UA005.039'
    - :term: 'Program in Women''s studies'
      :id: 'UA005.027'
    - :term: 'Center for Interdisciplinary Studies'
      :id: 'UA005.043'
    - :term: '[Other]'
      :id: 'other'

