terms:
  - id: MA
    term: 'Master of Arts'
  - id: MALD
    term: 'Master of Arts in Law and Diplomacy'
  - id: LLM
    term: 'Masters of Law in International Law'
  - id: MIB 
    term: 'Masters of International Business'
