terms:
  - id: http://purl.org/dc/dcmitype/Collection  
    term: Collection
  - id: http://purl.org/dc/dcmitype/Dataset
    term: Dataset
  - id: http://purl.org/dc/dcmitype/Event
    term: Event
  - id: http://purl.org/dc/dcmitype/Image
    term: Image
  - id: http://purl.org/dc/dcmitype/InteractiveResource
    term: InteractiveResource
  - id: http://purl.org/dc/dcmitype/MovingImage
    term: MovingImage
  - id: http://purl.org/dc/dcmitype/PhysicalObject
    term: PhysicalObject
  - id: http://purl.org/dc/dcmitype/Service
    term: Service
  - id: http://purl.org/dc/dcmitype/Software
    term: Software
  - id: http://purl.org/dc/dcmitype/StillImage
    term: StillImage
  - id: http://purl.org/dc/dcmitype/Text
    term: Text
