terms:
    - id: http://sites.tufts.edu/dca/about-us/research-help/reproductions-and-use/
      term: DCA Detailed Rights
      active: true
    - id: http://creativecommons.org/licenses/by/3.0/
      term: Attribution 3.0 United States
      active: true
    - id: https://creativecommons.org/licenses/by/4.0/
      term: Attribution 4.0 International
      active: true
    - id: http://bostonhistory.org/photorequest.html
      term: Bostonian Society License
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/
      term: Attribution-NonCommercial-ShareAlike 3.0
      active: true
    - id: http://www.aclweb.org/policies/resolutions.html
      term: Association for Computational Linguistics License
      active: true
    - id: http://www.acm.org/publications/policies/copyright_policy
      term: ACM Publishing Policy
      active: true
    - id: http://www.springer.com/authors/journal+authors?SGWID=0-154202-12-467999-0
      term: Springer Policy
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/2.5/
      term: Attribution-NonCommercial-ShareAlike 2.5 Generic
      active: true
    - id: http://creativecommons.org/licenses/by/2.0
      term: Attribution 2.0 Generic
      active: true
